# Generated by Django 3.2.7 on 2021-10-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmuestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelacionAlicuotasMedidas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('id_muestra', models.IntegerField(db_column='ID_MUESTRA')),
                ('id_alicuota', models.IntegerField(db_column='ID_ALICUOTA')),
                ('determinacion', models.IntegerField(db_column='DETERMINACION')),
                ('fecha_analisis', models.DateTimeField(db_column='FECHA_ANALISIS')),
                ('actividad', models.FloatField(blank=True, db_column='ACTIVIDAD', null=True)),
                ('actividad_error', models.FloatField(blank=True, db_column='ACTIVIDAD_ERROR', null=True)),
                ('amd', models.FloatField(blank=True, db_column='AMD', null=True)),
                ('tiempo_medida', models.IntegerField(blank=True, db_column='TIEMPO_MEDIDA', null=True)),
                ('cantidad', models.FloatField(blank=True, db_column='CANTIDAD', null=True)),
                ('rendimiento', models.IntegerField(blank=True, db_column='RENDIMIENTO', null=True)),
            ],
            options={
                'db_table': 'relacion_alicuotas_medidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionDeterminacionesProgramadas',
            fields=[
                ('identificador', models.AutoField(db_column='IDENTIFICADOR', primary_key=True, serialize=False)),
                ('determinacion_destino', models.IntegerField(db_column='DETERMINACION_DESTINO')),
                ('determinacion_origen', models.IntegerField(db_column='DETERMINACION_ORIGEN')),
                ('compuesta_de_uni', models.IntegerField(db_column='COMPUESTA_DE_UNI')),
                ('compuesta_de_mes', models.IntegerField(db_column='COMPUESTA_DE_MES')),
            ],
            options={
                'db_table': 'relacion_determinaciones_programadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelacionHistoricoAnaliticasCompuestas',
            fields=[
                ('identificador', models.AutoField(db_column='IDENTIFICADOR', primary_key=True, serialize=False)),
                ('determinacion_compuesta', models.IntegerField(db_column='DETERMINACION_COMPUESTA')),
                ('determinacion_parcial', models.IntegerField(db_column='DETERMINACION_PARCIAL')),
            ],
            options={
                'db_table': 'relacion_historico_analiticas_compuestas',
                'managed': False,
            },
        ),
    ]
