from django.urls import path
from django.conf.urls import url
from .views import *
from django.conf.urls.static import static
from django.conf.urls import url

app_name = 'public'

urlpatterns = [
    path('', homePublic, name='publicHome'),
    path('home',   homePublic),
    path('home/<slug:seccion>/', homePublicSeccion,  name='publicHomeSeccion'),
    path('laboratorios/', laboratorios, name='publicLaboratorios'),
    path('laboratorios/<slug:seccion>/', laboratoriosCompuesto,  name='publicLaboratoriosSeccion'),
    path('redes/', redes,  name='publicRedes'),
    path('redes/<slug:seccion>/', redesCompuesto, name='publicRedesSeccion'),
    path('noticias/', noticias, name='publicNoticias'),
    path('noticia/<slug:id>/', noticia, name='publicNoticia'),
    path('contacto/', contacto, name='publicContacto'),
    path('nosotros/', nosotros, name='publicNosotros'),
    path('RARE/',  rare, name='publicRAREx'),
    path('SPIDA/', spida, name='publicSPIDA'),
    path('consultaInforme/', consultaInforme),
    path('comprobacionInforme/', comprobacionInforme),
    path('idi/', publicaciones, name='publicPublicaciones'),
    path('idi/laboratorios', publicacionesLaboratorios, name='publicPublicacionesLaboratorios'),
    path('idi/redes', publicacionesRedes, name='publicPublicacionesRedes'),
    path('idi/<slug:tipo>/', filtrarPublicacion, name='publicFiltrarPublicaciones'),
    path('publicacion/<slug:id>/', publicacion, name='publicPublicacion'),
    path('thank-you-page/', gracias, name='publicGracias'),
    path('cursos/', cursos, name='publicCursos'),
    path('buscarNoticias/', buscarNoticias, name='publicBuscarNoticias'),
    path('buscarPublicacion/', buscarPublicacion, name='publicBuscarPublicacion'),
    path('form/<slug:id>/', formulario, name='publicFormulario'), 
    path('curso-info/<slug:id>/', cursoInfo, name='publicCursoInfo'),    
    path('solicitar-info/<slug:id>/', solicitarInfo, name='publicSolicitarInfo'),
    path('solicitar-contenido/<slug:id_curso>/<slug:codigo>/', solicitarContenido, name='publicSolicitarContenido'),
    path('formularioCurso/', formularioCurso, name='publicFormularioCurso'),

    # nuevos paths
    path('agregarNoticia/', agregarNoticia, name='publicAgregarNoticia'), 
    path('editarNoticia/<slug:id>', editarNoticia, name='publicEditarNoticia'), 
    path('eliminarNoticia/', eliminarNoticia, name='publicEliminarNoticia'),
    path('politicaCookies/', politicaCookies, name='publicPoliticaCookies'),
    path('noticiasFiltradas/<str:categorias>/', noticiasFiltradas, name='publicNoticiasFiltradas'),
    path('agregarServicio/', agregarServicio, name='publicAgregarServicio'),
    path('editarServicio/<slug:id>', editarServicio, name='publicEditarServicio'), 
    path('eliminarServicio/', eliminarServicio, name='publicEliminarServicio'),
    path('empleados/', empleados, name='publicEmpleados'),
    path('empleadoInfo/<slug:id>/', empleadoInfo, name='publicEmpleadoInfo'),
    path('editarEmpleado/', editarEmpleado, name='publicEditarEmpleado'),
    path('agregarEmpleado/', agregarEmpleado, name='publicAgregarEmpleado'),
    path('eliminarEmpleado/', eliminarEmpleado, name='publicEliminarEmpleado'),
    path('responsables/', responsables, name='publicResponsables'),
    path('responsableInfo/<slug:id>/', responsableInfo, name='publicResponsableInfo'),
    path('editarResponsable/', editarResponsable, name='publicEditarResponsable'),
    path('agregarResponsable/', agregarResponsable, name='publicAgregarResponsable'),
    path('eliminarResponsable/', eliminarResponsable, name='publicEliminarResponsable'),
    path('sliders/', sliders, name='publicSliders'),
    path('sliderInfo/<slug:id>/', sliderInfo, name='publicSliderInfo'),
    path('editarSlider/', editarSlider, name='publicEditarSlider'),
    path('agregarSlider/', agregarSlider, name='publicAgregarSlider'),
    path('eliminarSlider/', eliminarSlider, name='publicEliminarSlider'),
    path('acreditaciones/', acreditaciones, name='publicAcreditaciones'),
    path('acreditacionInfo/<slug:id>/', acreditacionInfo, name='publicAcreditacionInfo'),
    path('editarAcreditacion/', editarAcreditacion, name='publicEditarAcreditacion'),
    path('agregarAcreditacion/', agregarAcreditacion, name='publicAgregarAcreditacion'),
    path('eliminarAcreditacion/', eliminarAcreditacion, name='publicEliminarAcreditacion'),
    path('agregarInvestigacion/', agregarInvestigacion, name='publicAgregarInvestigacion'),  
    path('eliminarInvestigacion/', eliminarInvestigacion, name='publicEliminarInvestigacion'),
    path('nuestraHistoria/', nuestraHistoria, name='publicNuestraHistoria'),
    path('medidas/', medidas, name='publicMedidas'),
    path('nuestrasMedidas/', nuestrasMedidas, name='publicNuestrasMedidas'),
    path('medidas/<slug:url>/', medidaInfo, name='publicMedidaInfo'),
    path('agregarMedida/', agregarMedida, name='publicAgregarMedida'),
    path('editarMedida/<slug:id>', editarMedida, name='publicEditarMedida'),
    path('eliminarMedida/', eliminarMedida, name='publicEliminarMedida'),
    path('editarPublicacion/<slug:id>/', editarPublicacion, name='publicEditarPublicacion'),
    path('noticiasPrivadas/', noticiasPrivadas, name='publicNoticiasPrivadas'),
    
    path('private/servicios/', areaPrivada, name='servicios'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

