from django.urls import path
from rare.views import *
app_name = 'rare'


urlpatterns = [
    path('juntaex/rare/portada/', getPortadaRadiacion, name='juntaexPortadaRadiacion'),
    path('juntaex/', getPortadaRadiacion, name='juntaexPortada'),
    path('juntaex/vraex/', getPortadaRadiacion, name='juntaexPortadaVRAEX'),
    path('juntaex/rare/', getPortadaRadiacion, name='juntaexPortadaRarex'),
    path('juntaex/rare/mapMedia/',                      getMapaMedia,name='juntaexMapMediaRarex'),
    path('private/rare/',                      getPortadaRarex,name='rarexPortada'),
    path('private/rare/map/',                      getMapaEstado,name='rarexMapaEstado'),
    path('private/rare/mapLive/recarga/',                      getMapaEstadoActual ,name='getMapaEstadoActual'),
    path('private/rare/mapLive/recargaMensajes/',                      getUltimosMensajes ,name='getUltimosMensajes'),
    path('private/rare/mapLive/recargaMoviles/',                      getDispositivosMoviles ,name='getDispositivosMoviles'),
    path('private/rare/mapLive/recargaParametrosMoviles/<slug:id_estacion>/', getUltimoParametrosMovil ,name='getUltimoParametrosMovil'),
    path('private/rare/mapLive/recargaMovil/<slug:tipo>/<slug:id_estacion>/<slug:marker_id>/', getUltimoValorMovil ,name='getUltimoValorMovil'),
    path('private/rare/sesionesMedidaMovil/',                      getSesionesMedidaMovil,name='rarexSesionesMedidaMovil'),
    path('private/rare/sesionesMedidaCarga/',                      getSesionesMedidaMovilCarga,name='rarexSesionesMedidaMovilCarga'),
    path('private/rare/sesionMedida/<slug:id_sesion>/',                      getSesionMedida ,name='rarexSesionMedida'),
    path('private/rare/mapMedia/',                      getMapaMedia,name='rarexMapaMedia'),
    path('private/rare/mapMedia/recarga/',                      getValoresMedia,name='getValoresMedia'),
    path('private/rare/mapDrone/',                      getMapaDroneEstado,name='rarexMapaDrone'),
    path('private/rare/mapDrone/recarga/',                      getMapaDroneEstadoActual ,name='getMapaDroneActual'),
    path('private/rare/station/<slug:cod_estacion>/',       getStationData),
    path('private/rare/service/station/<slug:cod_estacion>/',       getStationDataService),
    path('private/rare/ubicacionesInteres/',       getUbicacionesInteres),
    path('private/rare/station/info/<slug:cod_estacion>/<slug:seccion>/',       getStationDataSection),
    path('private/rare/station/chartIsotope/<slug:id_detector>/<slug:id_isotopo>/',  getIsotopoEstacion),
    path('private/rare/station/chartChannel/<slug:id_estacion>/<slug:id_canal>/',  getCanalEstacion),
    path('private/rare/generacionInforme/',                      generacionInforme, name='rarexInformeCSN'),
    path('private/rare/guardiaRare/',                      getGuardiaRare, name='rarexGuardiaRare'),
    path('private/rare/consultaRare/',                      getConsultaRare, name='rarexConsultaRare'),
    path('private/rare/guardiaCSN/',                      getGuardiaCSN, name='rarexGuardiaCSN'),
    path('private/rare/consultaCSN/',                      getConsultaCSN, name='rarexConsultaCSN'),
    path('private/rare/guardiaSpida/',                      getGuardiaSpida, name='guardiaSpida'),
    path('private/rare/consultaSpida/',                      getConsultaSpida, name='consultaSpida'),
    path('private/rare/guardia/<slug:id_grupo>/<slug:id_subgrupo>/', getGuardiaGroup),
    path('private/rare/guardiaReload/<slug:id_chart>/', getChartReload),
    path('private/rare/guardiaResumen/', uploadResumenGuardia),
    path('private/rare/guardia/recalculoMedias/', solicitarCalculoMediasRareDosis),
    path('private/rare/infoGuardias/', infoGuardias, name='rarexInfoGuardias'),
    path('private/rare/invalidarDatos/<slug:id_chart>/<slug:anio>/',                      invalidarDatos),
    path('private/rare/invalidarDatosCSN/<slug:id_chart>/<slug:anio>/',                      invalidarDatosCSN),
    path('private/rare/invalidarDatoGamma/<slug:estacion>/<slug:canal>/<slug:fecha>/<slug:hora>/<slug:historico>/', invalidarDatoGamma),
    path('private/rare/invalidarDatoGammaCSN/<slug:estacion>/<slug:canal>/<slug:fecha>/<slug:hora>/<slug:historico>/', invalidarDatoGammaCSN),
    path('private/rare/invalidarDatoEspec/<slug:detector>/<slug:isotopo>/<slug:fecha>/<slug:hora>/<slug:todos>/<slug:historico>/', invalidarDatoEspec),
    path('private/rare/invalidarDatoEspecAcum/<slug:detector>/<slug:isotopo>/<slug:fecha>/<slug:hora>/<slug:todos>/<slug:historico>/', invalidarDatoEspecAcum),
    path('private/rare/invalidarDatoEspecCSN/<slug:detector>/<slug:isotopo>/<slug:fecha>/<slug:hora>/<slug:todos>/<slug:historico>/', invalidarDatoEspecCSN),
    path('private/rare/invalidarDatoEspecAcumCSN/<slug:detector>/<slug:isotopo>/<slug:fecha>/<slug:hora>/<slug:todos>/<slug:historico>/', invalidarDatoEspecAcumCSN),
    path('private/rare/informeGuardiaRARE/',                      informeGuardiaRare, name='informeGuardiaRARE'),
    path('private/rare/consultaCamarasPapel/',                      consultarImagenPapel, name='consultarImagenPapel'),
    path('private/rare/informe_rvra/',                      finalizarInformeRare, name='finalizarInformeRare'),
    path('private/rare/subidaFicheroChurro/', subirChurro, name='rarexSubidaChurro'),
    path('private/rare/monitoriza/',                      getMonitoriza, name='rarexMonitoriza'),
    path('private/rare/monitorizaDatos/',                      getMonitorizaDatos, name='rarexMonitorizaDatos'),
    path('private/rare/enviarMensajeMonitoriza/',                      enviarMensajeMonitoriza, name='rarexEnviarMensajeMonitoriza'),
    path('private/rare/modificarSeguimiento/<slug:parametro>/<slug:valor>/<slug:estacion>/<slug:canal>/<slug:isotopo>/', modificarSeguimiento, name='rarexModificarSeguimiento'),
    path('private/rare/mapaMedidas/<slug:id_mapa>/',                      medidasElHondon),
    path('private/rare/mapaMedidasHondon/',                      medidasElHondonJuan),
    path('private/rare/puntosMedida/',                      calcularPuntos),
    path('private/rare/proyectosMedida/',                      proyectosMedida, name='proyectosMedida'),
    path('informacionMedida/<slug:id>/', consultarInformacionMedida),
    path('recibirInformacion/', recepcionInformacionRedes),

    path('private/rare/simulacrosRealizados/',                      simulacrosRealizados, name='rarexSimulacrosRealizados'),
    path('private/rare/desactivarSimulacro/',                      desactivarSimulacro, name='rarexDesactivarSimulacro'),
    path('private/rare/informeSimulacro/<slug:id>/',                      informeSimulacro, name='rarexInformeSimulacro'),

    path('private/laruex/consultarConexionesRemotas/', consultarConexionesRemotas, name='consultarConexionesRemotas'),
    path('private/laruex/devolverConexionVNC/<slug:pc>/', devolverConexionVNC, name='devolverConexionVNC'),
    path('private/laruex/conexionesPorUsuario/', conexionesPorUsuario, name='conexionesPorUsuario'),
    path('private/laruex/conexionesPorEquipo/', conexionesPorEquipo, name='conexionesPorEquipo'),
    path('private/laruex/nuevaRelacionEquiposRemotosParaEquipo/', nuevaRelacionEquiposRemotosParaEquipo, name='nuevaRelacionEquiposRemotosParaEquipo'),
    path('private/laruex/nuevaRelacionEquiposRemotosParaUser/', nuevaRelacionEquiposRemotosParaUser, name='nuevaRelacionEquiposRemotosParaUser'),
    
]

